name: 'Release information for Slack'
description: 'Specific github app for sending release info to the Slack webhook'
inputs:
  json_from_github:
    description: 'Json content from github'
    required: true
    default: ''
  warn_message:
    description: 'Additional Warning message'
    required: false
    default: ''

runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: "orange"
  icon: "link-2"
