name: 'Github App for Slack'
description: 'Replace all links in given text with Slacks named link format'
inputs:
  json_from_github:
    description: 'Json content from github'
    required: true
    default: ''
outputs:
  modified_text:
    description: 'This output modified for named links'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  color: "orange"
  icon: "link-2"
