name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - test

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm test

  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: post a message to slack
      uses: ./
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        json_from_github: ${{ toJSON(github) }}
        warn_message: "[sample Warn message]"
